# Generated by Django 5.2.8 on 2026-02-06 23:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenteConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_asistente', models.CharField(default='Asistente Virtual', max_length=100, verbose_name='Nombre del asistente')),
                ('system_prompt', models.TextField(default='Sos un asistente virtual amable y profesional de una empresa de Revisión Técnica Vehicular (RTV). Respondés en español argentino, de forma clara, cálida y natural. Ayudás a los usuarios con consultas sobre turnos, tarifas, ubicación y servicios.', help_text='Personalidad e instrucciones base para la IA', verbose_name='Prompt del sistema')),
                ('ai_provider', models.CharField(choices=[('gemini_flash', 'Google Gemini Flash'), ('openai', 'OpenAI'), ('custom', 'Proveedor personalizado')], default='gemini_flash', max_length=20, verbose_name='Proveedor de IA')),
                ('ai_api_key', models.CharField(blank=True, help_text='Clave de API del proveedor seleccionado', max_length=255, verbose_name='API Key')),
                ('ai_model', models.CharField(default='gemini-2.0-flash', help_text='Nombre del modelo a utilizar', max_length=100, verbose_name='Modelo de IA')),
                ('max_tokens_per_request', models.IntegerField(default=300, verbose_name='Máx. tokens por solicitud')),
                ('timeout_seconds', models.IntegerField(default=10, help_text='Tiempo máximo de espera para la respuesta de la IA', verbose_name='Timeout (segundos)')),
                ('max_ai_calls_per_session', models.IntegerField(default=20, verbose_name='Máx. llamadas IA por sesión')),
                ('max_ai_calls_per_day', models.IntegerField(default=500, verbose_name='Máx. llamadas IA por día')),
                ('umbral_cache_similarity', models.FloatField(default=0.85, help_text='Valor entre 0 y 1. A mayor valor, más exacta debe ser la coincidencia para usar cache.', verbose_name='Umbral similitud cache')),
                ('mensaje_bienvenida', models.TextField(default='¡Hola! Soy el asistente virtual de RTV Pioli. ¿En qué puedo ayudarte? Podés preguntarme sobre turnos, tarifas, ubicación o nuestros servicios.', verbose_name='Mensaje de bienvenida')),
                ('mensaje_fuera_dominio', models.TextField(default='Disculpá, solo puedo ayudarte con temas relacionados a la Revisión Técnica Vehicular: turnos, tarifas, ubicación y servicios. ¿Hay algo de eso en lo que pueda asistirte?', verbose_name='Mensaje fuera de dominio')),
                ('mensaje_error', models.TextField(default='Perdón, tuve un problema procesando tu consulta. Por favor intentá de nuevo o contactanos por WhatsApp.', verbose_name='Mensaje de error')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Asistente habilitado')),
                ('status', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Configuración del Asistente',
                'verbose_name_plural': 'Configuración del Asistente',
            },
        ),
        migrations.CreateModel(
            name='CachedResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta_normalizada', models.CharField(max_length=500, verbose_name='Pregunta normalizada')),
                ('intent', models.CharField(max_length=50, verbose_name='Intención')),
                ('datos_contexto', models.JSONField(blank=True, default=dict, verbose_name='Datos de contexto usados')),
                ('respuesta', models.TextField(verbose_name='Respuesta cacheada')),
                ('veces_usada', models.IntegerField(default=0, verbose_name='Veces utilizada')),
                ('vigente', models.BooleanField(default=True, verbose_name='Vigente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Respuesta en Cache',
                'verbose_name_plural': 'Respuestas en Cache',
                'ordering': ['-veces_usada'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100, unique=True, verbose_name='Clave de sesión')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('inicio', models.DateTimeField(auto_now_add=True, verbose_name='Inicio')),
                ('ultima_actividad', models.DateTimeField(auto_now=True, verbose_name='Última actividad')),
                ('ai_calls_count', models.IntegerField(default=0, verbose_name='Llamadas IA')),
                ('contexto', models.JSONField(blank=True, default=dict, verbose_name='Contexto de la conversación')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Sesión de Chat',
                'verbose_name_plural': 'Sesiones de Chat',
                'ordering': ['-ultima_actividad'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=500, verbose_name='Pregunta')),
                ('palabras_clave', models.JSONField(blank=True, default=list, help_text='Lista de palabras clave para matching. Ej: ["tarifa", "precio", "costo"]', verbose_name='Palabras clave')),
                ('respuesta_datos', models.TextField(help_text='Respuesta con los datos concretos que el asistente usará', verbose_name='Respuesta (datos)')),
                ('respuesta_humanizada', models.TextField(blank=True, help_text='Versión humanizada por IA (se genera automáticamente)', verbose_name='Respuesta humanizada (cache)')),
                ('categoria', models.CharField(choices=[('turnos', 'Turnos'), ('tarifas', 'Tarifas'), ('ubicacion', 'Ubicación'), ('servicios', 'Servicios'), ('horarios', 'Horarios'), ('general', 'General')], default='general', max_length=20, verbose_name='Categoría')),
                ('origen', models.CharField(choices=[('manual', 'Manual'), ('sugerida_ia', 'Sugerida por IA')], default='manual', max_length=20, verbose_name='Origen')),
                ('veces_usada', models.IntegerField(default=0, verbose_name='Veces utilizada')),
                ('aprobada', models.BooleanField(default=True, verbose_name='Aprobada')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
                ('status', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Pregunta Frecuente',
                'verbose_name_plural': 'Preguntas Frecuentes',
                'ordering': ['orden', '-veces_usada'],
            },
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50, verbose_name='Proveedor')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('tokens_input', models.IntegerField(default=0, verbose_name='Tokens entrada')),
                ('tokens_output', models.IntegerField(default=0, verbose_name='Tokens salida')),
                ('costo_estimado', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='Costo estimado (USD)')),
                ('latencia_ms', models.IntegerField(default=0, verbose_name='Latencia (ms)')),
                ('exitoso', models.BooleanField(default=True, verbose_name='Exitoso')),
                ('error_mensaje', models.TextField(blank=True, verbose_name='Mensaje de error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asistente.chatsession', verbose_name='Sesión')),
            ],
            options={
                'verbose_name': 'Log de Uso IA',
                'verbose_name_plural': 'Logs de Uso IA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Asistente')], max_length=10, verbose_name='Rol')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('intent', models.CharField(blank=True, max_length=50, null=True, verbose_name='Intención detectada')),
                ('source', models.CharField(blank=True, choices=[('faq', 'FAQ'), ('cache', 'Cache'), ('db', 'Base de datos'), ('ai', 'Inteligencia Artificial'), ('hardcoded', 'Respuesta fija')], max_length=20, null=True, verbose_name='Fuente de la respuesta')),
                ('tokens_usados', models.IntegerField(default=0, verbose_name='Tokens usados')),
                ('tiempo_respuesta_ms', models.IntegerField(default=0, verbose_name='Tiempo de respuesta (ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='asistente.chatsession', verbose_name='Sesión')),
                ('faq_usada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asistente.faq', verbose_name='FAQ utilizada')),
            ],
            options={
                'verbose_name': 'Mensaje de Chat',
                'verbose_name_plural': 'Mensajes de Chat',
                'ordering': ['created_at'],
            },
        ),
    ]
