# Generated by Django 5.2.8 on 2026-02-07 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistente', '0003_fix_icon_asistente'),
        ('talleres', '0016_taller_whatsapp_operador'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenteconfigmodel',
            name='email_resumen_semanal',
            field=models.EmailField(blank=True, help_text='Recibe un resumen semanal de sugerencias y consultas no resueltas', max_length=254, verbose_name='Email para resumen semanal'),
        ),
        migrations.CreateModel(
            name='Derivacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email')], max_length=10, verbose_name='Canal de derivación')),
                ('motivo', models.TextField(blank=True, verbose_name='Resumen de la conversación')),
                ('celular_cliente', models.CharField(blank=True, help_text='Número que dejó el cliente para ser contactado', max_length=20, verbose_name='Celular del cliente')),
                ('en_horario', models.BooleanField(default=True, verbose_name='Dentro del horario de atención')),
                ('email_enviado', models.BooleanField(default=False, verbose_name='Email enviado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derivaciones', to='asistente.chatsession', verbose_name='Sesión')),
                ('taller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='talleres.taller', verbose_name='Taller')),
            ],
            options={
                'verbose_name': 'Derivación a Operador',
                'verbose_name_plural': 'Derivaciones a Operador',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SugerenciaAsistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=200, verbose_name='Tema')),
                ('tema_normalizado', models.CharField(max_length=200, verbose_name='Tema normalizado')),
                ('categoria', models.CharField(choices=[('funcionalidad', 'Funcionalidad'), ('informacion', 'Información'), ('servicio', 'Servicio'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Categoría')),
                ('estado', models.CharField(choices=[('nueva', 'Nueva'), ('revisada', 'Revisada'), ('planificada', 'Planificada'), ('implementada', 'Implementada'), ('descartada', 'Descartada')], default='nueva', max_length=20, verbose_name='Estado')),
                ('veces_detectada', models.IntegerField(default=1, verbose_name='Veces detectada')),
                ('ultimo_ejemplo', models.TextField(blank=True, verbose_name='Último mensaje ejemplo')),
                ('notas_admin', models.TextField(blank=True, verbose_name='Notas del administrador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de detección')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('session_ejemplo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asistente.chatsession', verbose_name='Sesión ejemplo')),
            ],
            options={
                'verbose_name': 'Sugerencia del Asistente',
                'verbose_name_plural': 'Sugerencias del Asistente',
                'ordering': ['-veces_detectada', '-updated_at'],
            },
        ),
    ]
