# Generated by Django 5.2.8 on 2026-02-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistente', '0004_asistenteconfigmodel_email_resumen_semanal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenteconfigmodel',
            name='auto_open_delay',
            field=models.IntegerField(default=3000, help_text='Milisegundos que el chat permanece abierto al cargar la página. 0 = deshabilitado.', verbose_name='Auto-apertura (ms)'),
        ),
    ]
