# Generated by Django 5.2.8 on 2026-02-07 16:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistente', '0005_add_auto_open_delay'),
    ]

    operations = [
        migrations.CreateModel(
            name='SugerenciaToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token')),
                ('accion', models.CharField(choices=[('implementar', 'Implementar'), ('declinar', 'Declinar')], max_length=20, verbose_name='Acción')),
                ('usado', models.BooleanField(default=False, verbose_name='Usado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('expires_at', models.DateTimeField(verbose_name='Fecha de expiración')),
                ('sugerencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='asistente.sugerenciaasistente', verbose_name='Sugerencia')),
            ],
            options={
                'verbose_name': 'Token de Sugerencia',
                'verbose_name_plural': 'Tokens de Sugerencia',
            },
        ),
    ]
