# Generated by Django 5.2.8 on 2026-02-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistente', '0006_add_sugerencia_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoKB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('categoria', models.CharField(choices=[('procedimiento', 'Procedimiento'), ('normativa', 'Normativa'), ('manual', 'Manual'), ('informe', 'Informe'), ('general', 'General')], default='general', max_length=20, verbose_name='Categoría')),
                ('archivo', models.FileField(blank=True, help_text='PDF, Word o texto. Se extrae el contenido automáticamente.', null=True, upload_to='asistente/kb/', verbose_name='Archivo fuente')),
                ('contenido_texto', models.TextField(blank=True, help_text='Texto del documento. Se llena automáticamente al subir archivo, o manualmente.', verbose_name='Contenido')),
                ('palabras_clave', models.JSONField(blank=True, default=list, help_text='Lista de keywords para búsqueda. Se generan automáticamente.', verbose_name='Palabras clave')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('veces_usado', models.PositiveIntegerField(default=0, verbose_name='Veces utilizado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Documento KB',
                'verbose_name_plural': 'Documentos KB',
                'ordering': ['-updated_at'],
            },
        ),
    ]
