# Generated by Django 5.2.8 on 2026-02-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistente', '0007_documentokb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='source',
            field=models.CharField(blank=True, choices=[('faq', 'FAQ'), ('cache', 'Cache'), ('db', 'Base de datos'), ('ai', 'Inteligencia Artificial'), ('kb+ai', 'Base de Conocimiento + IA'), ('hardcoded', 'Respuesta fija')], max_length=20, null=True, verbose_name='Fuente de la respuesta'),
        ),
    ]
