# Generated by Django 5.2.8 on 2026-02-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistente', '0009_agregar_menu_kb'),
    ]

    operations = [
        migrations.AddField(
            model_name='derivacion',
            name='email_cliente',
            field=models.EmailField(blank=True, default='', help_text='Email que dejó el cliente para ser contactado', max_length=254, verbose_name='Email del cliente'),
        ),
    ]
