# Generated by Django 5.0.2 on 2025-11-06 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de recepción')),
                ('read', models.BooleanField(default=False, verbose_name='Leído')),
                ('replied', models.BooleanField(default=False, verbose_name='Respondido')),
            ],
            options={
                'verbose_name': 'Mensaje de Contacto',
                'verbose_name_plural': 'Mensajes de Contacto',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('subtitle', models.CharField(max_length=100, verbose_name='Subtítulo/Categoría')),
                ('thumbnail', models.ImageField(upload_to='portfolio/thumbnails/', verbose_name='Imagen miniatura')),
                ('full_image', models.ImageField(upload_to='portfolio/full/', verbose_name='Imagen completa')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('client', models.CharField(max_length=100, verbose_name='Cliente')),
                ('category', models.CharField(max_length=100, verbose_name='Categoría')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Item de Portafolio',
                'verbose_name_plural': 'Items de Portafolio',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Clase de FontAwesome (ej: fa-shopping-cart)', max_length=50)),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Agency', max_length=200, verbose_name='Título del sitio')),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Logo')),
                ('hero_title', models.CharField(default="It's Nice To Meet You", max_length=200, verbose_name='Título del Hero')),
                ('hero_subtitle', models.CharField(default='Welcome To Our Studio!', max_length=200, verbose_name='Subtítulo del Hero')),
                ('hero_button_text', models.CharField(default='Tell Me More', max_length=50, verbose_name='Texto del botón')),
                ('footer_copyright', models.CharField(default='Copyright © Your Website 2024', max_length=200, verbose_name='Copyright del footer')),
                ('twitter_url', models.URLField(blank=True, verbose_name='URL de Twitter')),
                ('facebook_url', models.URLField(blank=True, verbose_name='URL de Facebook')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='URL de LinkedIn')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contacto')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de contacto')),
                ('contact_address', models.TextField(blank=True, verbose_name='Dirección')),
                ('primary_color', models.CharField(default='#ffc800', help_text='Formato hex (ej: #ffc800)', max_length=7, verbose_name='Color primario')),
                ('secondary_color', models.CharField(default='#000000', help_text='Formato hex (ej: #000000)', max_length=7, verbose_name='Color secundario')),
                ('font_family', models.CharField(choices=[('Montserrat', 'Montserrat'), ('Roboto', 'Roboto'), ('Open Sans', 'Open Sans'), ('Lato', 'Lato'), ('Poppins', 'Poppins')], default='Montserrat', max_length=50, verbose_name='Fuente principal')),
                ('base_font_size', models.IntegerField(default=16, verbose_name='Tamaño base (px)')),
                ('heading_font_size_h1', models.IntegerField(default=40, verbose_name='Tamaño H1 (px)')),
                ('heading_font_size_h2', models.IntegerField(default=32, verbose_name='Tamaño H2 (px)')),
                ('heading_font_size_h3', models.IntegerField(default=24, verbose_name='Tamaño H3 (px)')),
                ('heading_font_size_h4', models.IntegerField(default=18, verbose_name='Tamaño H4 (px)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sitio',
                'verbose_name_plural': 'Configuración del Sitio',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('position', models.CharField(max_length=100, verbose_name='Cargo/Posición')),
                ('photo', models.ImageField(upload_to='team/', verbose_name='Foto')),
                ('twitter_url', models.URLField(blank=True, verbose_name='URL de Twitter')),
                ('facebook_url', models.URLField(blank=True, verbose_name='URL de Facebook')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='URL de LinkedIn')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Miembro del Equipo',
                'verbose_name_plural': 'Miembros del Equipo',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50, verbose_name='Fecha/Período')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='timeline/', verbose_name='Imagen')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('inverted', models.BooleanField(default=False, help_text='Alterna el lado de visualización', verbose_name='Invertido')),
                ('is_final', models.BooleanField(default=False, help_text="Marca si es el último item 'Be Part Of Our Story'", verbose_name='Es el item final')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evento de Línea de Tiempo',
                'verbose_name_plural': 'Eventos de Línea de Tiempo',
                'ordering': ['order', 'date'],
            },
        ),
    ]
