# Generated by Django 5.0.2 on 2025-11-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='header_background',
            field=models.ImageField(blank=True, null=True, upload_to='site/header/', verbose_name='Imagen de fondo del header'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='font_family',
            field=models.CharField(choices=[('Montserrat', 'Montserrat'), ('Roboto', 'Roboto'), ('Open Sans', 'Open Sans'), ('Lato', 'Lato'), ('Poppins', 'Poppins')], default='Poppins', max_length=50, verbose_name='Fuente principal'),
        ),
    ]
