# Generated by Django 5.0.2 on 2025-11-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_siteconfiguration_header_background_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='header_background_video',
            field=models.FileField(blank=True, help_text='Formato recomendado: MP4, WebM. El video se mostrará en lugar de la imagen si está presente.', null=True, upload_to='site/header/video/', verbose_name='Video de fondo del header'),
        ),
    ]
# Eliminado para limpieza de migraciones
