# Generated by Django 5.0.2 on 2025-11-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_siteconfiguration_header_background_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='header_video_brightness',
            field=models.FloatField(default=0.5, help_text='Valor entre 0 (oscuro) y 1 (normal). Recomendado: 0.3 a 0.7', verbose_name='Brillo del video de fondo'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='header_video_contrast',
            field=models.FloatField(default=1.0, help_text='Valor 1 = normal, menor para menos contraste, mayor para más contraste.', verbose_name='Contraste del video de fondo'),
        ),
    ]
# Eliminado para limpieza de migraciones
