# Generated by Django 5.0.2 on 2025-11-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_siteconfiguration_header_video_brightness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='header_video_height',
            field=models.CharField(default='100%', help_text='Ejemplo: 100%, 600px, 50vh', max_length=10, verbose_name='Alto del video de fondo'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='header_video_width',
            field=models.CharField(default='100%', help_text='Ejemplo: 100%, 1920px, 80vw', max_length=10, verbose_name='Ancho del video de fondo'),
        ),
    ]
