# Generated by Django 5.0.2 on 2025-11-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_siteconfiguration_header_video_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='header_btn1_text',
            field=models.CharField(default='Turno Planta Palpalá', max_length=100, verbose_name='Texto botón 1'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='header_btn1_url',
            field=models.URLField(default='https://turnos.redsoft.com.ar/agen', verbose_name='URL botón 1'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='header_btn2_text',
            field=models.CharField(default='Turno Planta Libertador', max_length=100, verbose_name='Texto botón 2'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='header_btn2_url',
            field=models.URLField(default='https://turnos.redsoft.com.ar/agenda/calendario', verbose_name='URL botón 2'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='header_btn_bgcolor',
            field=models.CharField(default='#02197A', help_text='Formato hex (ej: #02197A)', max_length=7, verbose_name='Color de fondo de los botones'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='service_icon_bgcolor',
            field=models.CharField(default='#ffc800', help_text='Ejemplo: #ffc800 o text-primary', max_length=20, verbose_name='Color de fondo del ícono (círculo)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='service_icon_fgcolor',
            field=models.CharField(default='#02197A', help_text='Ejemplo: #02197A o text-inverse', max_length=20, verbose_name='Color del ícono (FA)'),
        ),
    ]
