# Generated by Django 5.0.2 on 2025-11-09 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_siteconfiguration_header_btn1_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioitem',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Portafolio', 'verbose_name_plural': 'Portafolios'},
        ),
    ]
# Eliminado para limpieza de migraciones
