# Generated by Django 5.0.2 on 2025-11-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_portfolioitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='portfolio_hover_bgcolor',
            field=models.CharField(default='#e0e0e0', help_text='Ejemplo: #e0e0e0, #ffffff, rgba(0,0,0,0.1)', max_length=20, verbose_name='Color de fondo hover en portfolio'),
        ),
    ]
# Eliminado para limpieza de migraciones
