# Generated by Django 5.0.2 on 2025-11-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_siteconfiguration_portfolio_hover_bgcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='contact_section_bg_color',
            field=models.CharField(default='#212529', help_text='Ejemplo: #212529, #ffffff, rgba(0,0,0,0.1)', max_length=20, verbose_name='Color de fondo de la sección contacto'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='contact_section_bg_image',
            field=models.ImageField(blank=True, help_text='Imagen que se mostrará como fondo en la sección contacto. Tiene prioridad sobre el color.', null=True, upload_to='contact_bg/', verbose_name='Imagen de fondo de la sección contacto'),
        ),
    ]
# Eliminado para limpieza de migraciones
