# Generated by Django 5.0.2 on 2025-11-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_siteconfiguration_contact_section_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='contact_btn_bgcolor',
            field=models.CharField(default='#ffc800', help_text='Ejemplo: #ffc800, #212529, rgba(255,200,0,0.9)', max_length=20, verbose_name='Color de fondo del botón de contacto'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='contact_btn_fgcolor',
            field=models.CharField(default='#212529', help_text='Ejemplo: #fff, #212529', max_length=20, verbose_name='Color de texto del botón de contacto'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='contact_btn_text',
            field=models.CharField(default='Enviar Mensaje', help_text='Texto que aparece en el botón de enviar del formulario de contacto.', max_length=50, verbose_name='Texto del botón de contacto'),
        ),
    ]
# Eliminado para limpieza de migraciones
