# Generated by Django 5.0.2 on 2025-11-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_siteconfiguration_contact_btn_bgcolor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='contact_btn_hover_bgcolor',
            field=models.CharField(default='#ffd700', help_text='Color de fondo del botón cuando el mouse pasa por encima. Ejemplo: #ffd700, #212529, rgba(255,200,0,0.9)', max_length=20, verbose_name='Color de fondo del botón de contacto (hover)'),
        ),
    ]
# Eliminado para limpieza de migraciones
