# Generated by Django 5.0.2 on 2025-11-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_siteconfiguration_contact_btn_hover_bgcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_card_bg_color',
            field=models.CharField(default='#212529', help_text='Ejemplo: #212529, #ffffff, rgba(0,0,0,0.1)', max_length=20, verbose_name='Color de fondo de la card hero'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_card_bg_image',
            field=models.ImageField(blank=True, help_text='Imagen que se mostrará como fondo en la card hero. Tiene prioridad sobre el color.', null=True, upload_to='hero_card_bg/', verbose_name='Imagen de fondo de la card hero'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_card_elevation',
            field=models.CharField(default='8px', help_text='Ejemplo: 8px, 16px', max_length=10, verbose_name='Elevación (sombra) de la card hero'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_card_hover_elevation',
            field=models.CharField(default='24px', help_text='Ejemplo: 24px, 32px', max_length=10, verbose_name='Elevación hover de la card hero'),
        ),
    ]
# Eliminado para limpieza de migraciones
