# Generated by Django 5.0.2 on 2025-11-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_siteconfiguration_hero_card_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_card_bg_opacity',
            field=models.FloatField(default=0.85, help_text='Valor entre 0 (transparente) y 1 (opaco). Ejemplo: 0.85', verbose_name='Opacidad del fondo de la card hero'),
        ),
    ]
# Eliminado para limpieza de migraciones
