# Generated by Django 5.0.2 on 2025-11-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_siteconfiguration_hero_card_bg_opacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='contact_section_bg_opacity',
            field=models.FloatField(default=1.0, help_text='Valor entre 0 (transparente) y 1 (opaco).', verbose_name='Opacidad de fondo de la sección contacto'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='contact_section_bg_video',
            field=models.FileField(blank=True, help_text='Formato recomendado: MP4, WebM. El video se mostrará en lugar de la imagen si está presente.', null=True, upload_to='contact_bg/video/', verbose_name='Video de fondo de la sección contacto'),
        ),
    ]
