# Generated by Django 5.0.2 on 2025-11-09 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_siteconfiguration_contact_section_bg_opacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='navbar_bg_color_scrolled',
            field=models.CharField(default='#272EF5', help_text='Ejemplo: #272EF5, #ffffff, rgba(0,0,0,0.1)', max_length=20, verbose_name='Color de fondo del navbar al hacer scroll'),
        ),
    ]
# Eliminado para limpieza de migraciones
