# Generated by Django 5.0.2 on 2025-11-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_siteconfiguration_navbar_bg_color_scrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='excel_file',
            field=models.FileField(blank=True, help_text='Sube una tabla de precios en formato Excel (xlsx, xls). Se mostrará como tabla en la descripción si está presente.', null=True, upload_to='service/excel/', verbose_name='Archivo Excel de tabla de precios'),
        ),
    ]
# Eliminado para limpieza de migraciones
