# Generated by Django 5.0.2 on 2025-11-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_service_excel_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='excel_file',
        ),
        migrations.AddField(
            model_name='service',
            name='attachment',
            field=models.FileField(blank=True, help_text='Sube un archivo adjunto (Excel, Word, imagen, etc). Se mostrará en la descripción si está presente.', null=True, upload_to='service/attachments/', verbose_name='Archivo adjunto'),
        ),
    ]
# Eliminado para limpieza de migraciones
