# Generated by Django 5.0.2 on 2025-11-16 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_service_excel_file_service_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Sección Nosotros',
                'verbose_name_plural': 'Sección Nosotros',
            },
        ),
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about_images/', verbose_name='Imagen')),
                ('about_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.aboutsection')),
            ],
            options={
                'verbose_name': 'Imagen de Nosotros',
                'verbose_name_plural': 'Imágenes de Nosotros',
            },
        ),
    ]
