# Generated by Django 5.0.2 on 2025-11-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_aboutsection_aboutimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='¿Mostrar título?'),
        ),
    ]
# Eliminado para limpieza de migraciones
