# Generated by Django 5.0.2 on 2025-11-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_aboutsection_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='header_btns_text',
            field=models.CharField(blank=True, help_text='Texto breve que se muestra sobre los botones de turno. Ejemplo: "Listo para solicitar tu turno? Ver tutorial"', max_length=120, null=True, verbose_name='Texto sobre los botones de turno'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='header_btns_video',
            field=models.FileField(blank=True, help_text='Video tutorial que se muestra al hacer clic en "Ver tutorial".', null=True, upload_to='tutorial_videos/', verbose_name='Video tutorial de turnos'),
        ),
    ]
