# Generated by Django 5.0.2 on 2025-11-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_siteconfiguration_header_btns_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='header_btns_text_color',
            field=models.CharField(default='#fff', help_text='Color del texto sobre los botones de turno. Ejemplo: #fff, #003466, #ffd700', max_length=20, verbose_name='Color del texto tutorial sobre los botones'),
        ),
    ]
# Eliminado para limpieza de migraciones
