# Generated by Django 5.0.2 on 2025-11-16 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_siteconfiguration_header_btns_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='show_hero_subtitle',
            field=models.BooleanField(default=True, help_text='Si está desactivado, el subtítulo del Hero no se mostrará.', verbose_name='¿Mostrar subtítulo del Hero?'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='show_hero_title',
            field=models.BooleanField(default=True, help_text='Si está desactivado, el título principal del Hero no se mostrará.', verbose_name='¿Mostrar título del Hero?'),
        ),
    ]
# Eliminado para limpieza de migraciones
