# Generated by Django 5.0.2 on 2025-11-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_siteconfiguration_show_hero_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_subtitle',
            field=models.CharField(blank=True, default='Welcome To Our Studio!', max_length=200, null=True, verbose_name='Subtítulo del Hero'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_title',
            field=models.CharField(blank=True, default="It's Nice To Meet You", max_length=200, null=True, verbose_name='Título del Hero'),
        ),
    ]
