# Generated by Django 5.0.2 on 2025-11-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_siteconfiguration_hero_subtitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(default='smtp-mail.outlook.com', max_length=255, verbose_name='Servidor SMTP')),
                ('email_port', models.PositiveIntegerField(default=587, verbose_name='Puerto SMTP')),
                ('email_use_tls', models.BooleanField(default=True, verbose_name='Usar TLS')),
                ('email_host_user', models.EmailField(max_length=255, verbose_name='Usuario (correo)')),
                ('email_host_password', models.CharField(blank=True, max_length=255, verbose_name='Contraseña')),
                ('default_from_email', models.EmailField(blank=True, max_length=255, verbose_name='Correo remitente')),
                ('contact_admin_email', models.EmailField(blank=True, max_length=255, verbose_name='Correo destinatario')),
            ],
            options={
                'verbose_name': 'Configuración de correo',
                'verbose_name_plural': 'Configuración de correo',
            },
        ),
    ]
