# Generated by Django 5.0.2 on 2025-11-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_whatsappconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutimage',
            options={'verbose_name': 'Imagen de Seccion Nosotros', 'verbose_name_plural': 'Imágenes de Seccion Nosotros'},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mensaje de Seccion Contacto', 'verbose_name_plural': 'Mensajes de Seccion Contacto'},
        ),
        migrations.AlterModelOptions(
            name='emailconfig',
            options={'verbose_name': 'Configuración de Correo', 'verbose_name_plural': 'Configuración de Correo'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Seccion Servicio', 'verbose_name_plural': 'Seccion Servicios'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Seccion Miembro Equipo', 'verbose_name_plural': 'Seccion Miembros Equipo'},
        ),
        migrations.AlterModelOptions(
            name='whatsappconfig',
            options={'verbose_name': 'Configuración WhatsApp', 'verbose_name_plural': 'Configuración WhatsApp'},
        ),
        migrations.RemoveField(
            model_name='whatsappconfig',
            name='numero',
        ),
        migrations.AddField(
            model_name='whatsappconfig',
            name='codigo_pais',
            field=models.CharField(default='+54', max_length=6, verbose_name='Código de país'),
        ),
        migrations.AddField(
            model_name='whatsappconfig',
            name='numero_internacional',
            field=models.CharField(blank=True, editable=False, max_length=20, verbose_name='Número internacional'),
        ),
        migrations.AddField(
            model_name='whatsappconfig',
            name='numero_local',
            field=models.CharField(default='', max_length=20, verbose_name='Número local'),
        ),
        migrations.AddField(
            model_name='whatsappconfig',
            name='pais',
            field=models.CharField(default='Argentina', max_length=50, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='whatsappconfig',
            name='provincia',
            field=models.CharField(blank=True, max_length=50, verbose_name='Provincia'),
        ),
    ]
