# Generated by Django 5.2.8 on 2025-12-09 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_aboutimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='URL de Instagram'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='twitter_url',
            field=models.URLField(blank=True, verbose_name='URL de X (Twitter)'),
        ),
    ]
