# Generated by Django 5.2.8 on 2026-01-16 03:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_siteconfiguration_instagram_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailconfig',
            options={'ordering': ['-es_principal', 'nombre'], 'verbose_name': 'Configuración de Correo', 'verbose_name_plural': 'Configuraciones de Correo'},
        ),
        migrations.AddField(
            model_name='emailconfig',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='emailconfig',
            name='es_principal',
            field=models.BooleanField(default=False, help_text='Solo una configuración puede ser la principal. Se usará para enviar correos del sistema.', verbose_name='¿Es la configuración principal?'),
        ),
        migrations.AddField(
            model_name='emailconfig',
            name='nombre',
            field=models.CharField(default='Configuración Principal', help_text='Identificador para esta configuración (ej: "Correo Principal", "Correo Turnos")', max_length=100, verbose_name='Nombre de la configuración'),
        ),
        migrations.AddField(
            model_name='emailconfig',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='emailconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
    ]
