# Generated by Django 5.2.8 on 2026-01-04 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('territorios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: RTO: AUTOS - PICK UP - UTILITARIO', max_length=100, verbose_name='Nombre del Trámite')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('duracion_minutos', models.IntegerField(default=30, help_text='Tiempo estimado para completar la inspección', verbose_name='Duración (minutos)')),
                ('precio', models.DecimalField(decimal_places=2, default=0, help_text='Precio del trámite en pesos', max_digits=10, verbose_name='Precio')),
                ('status', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de Vehículo',
                'verbose_name_plural': 'Tipos de Vehículos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Taller')),
                ('direccion', models.CharField(max_length=300, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('latitud', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Latitud')),
                ('longitud', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Longitud')),
                ('horario_apertura', models.TimeField(verbose_name='Hora de Apertura')),
                ('horario_cierre', models.TimeField(verbose_name='Hora de Cierre')),
                ('dias_atencion', models.JSONField(default=dict, help_text='Formato: {"lunes": True, "martes": True, "miercoles": True, ...}', verbose_name='Días de Atención')),
                ('status', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='territorios.localidad', verbose_name='Localidad')),
            ],
            options={
                'verbose_name': 'Taller',
                'verbose_name_plural': 'Talleres',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio', models.CharField(help_text='Patente del vehículo (ej: ABC123 o AB123CD)', max_length=10, unique=True, verbose_name='Dominio')),
                ('tiene_gnc', models.BooleanField(default=False, help_text='Indica si el vehículo tiene instalación de Gas Natural Comprimido', verbose_name='¿Tiene GNC?')),
                ('status', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('cliente', models.ForeignKey(help_text='Cliente responsable del vehículo', on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='clientes.cliente', verbose_name='Cliente (Titular)')),
                ('tipo_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleres.tipovehiculo', verbose_name='Tipo de Vehículo')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['dominio'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turnos_simultaneos', models.IntegerField(default=3, help_text='Cantidad de vehículos que pueden atenderse al mismo tiempo', verbose_name='Turnos Simultáneos')),
                ('intervalo_minutos', models.IntegerField(default=15, help_text='Tiempo entre cada turno disponible', verbose_name='Intervalo entre turnos (minutos)')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones', to='talleres.taller', verbose_name='Taller')),
                ('tipo_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleres.tipovehiculo', verbose_name='Tipo de Vehículo')),
            ],
            options={
                'verbose_name': 'Configuración de Taller',
                'verbose_name_plural': 'Configuraciones de Talleres',
                'unique_together': {('taller', 'tipo_vehiculo')},
            },
        ),
    ]
