# Generated by Django 5.2.8 on 2026-01-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='latitud',
            field=models.DecimalField(decimal_places=12, max_digits=15, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='longitud',
            field=models.DecimalField(decimal_places=12, max_digits=15, verbose_name='Longitud'),
        ),
    ]
