# Generated by Django 5.2.8 on 2026-01-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0002_alter_taller_latitud_alter_taller_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='latitud',
            field=models.DecimalField(decimal_places=15, max_digits=18, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='longitud',
            field=models.DecimalField(decimal_places=15, max_digits=18, verbose_name='Longitud'),
        ),
    ]
