# Generated by Django 5.2.8 on 2026-01-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0003_alter_taller_latitud_alter_taller_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='dias_atencion',
            field=models.JSONField(default=dict, help_text='Formato: {"lunes": true, "martes": true, "miercoles": true, ...}', verbose_name='Días de Atención'),
        ),
    ]
