# Generated by Django 5.2.8 on 2026-01-04 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0004_alter_taller_dias_atencion'),
        ('territorios', '0001_initial'),
        ('ubicacion', '0004_ubicacion_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='planta',
            field=models.ForeignKey(blank=True, help_text='Si se selecciona una planta, se usarán sus datos de ubicación y contacto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talleres', to='ubicacion.ubicacion', verbose_name='Planta/Ubicación'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='direccion',
            field=models.CharField(blank=True, max_length=300, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='territorios.localidad', verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, verbose_name='Teléfono'),
        ),
    ]
