# Generated by Django 5.2.8 on 2026-01-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0005_taller_planta_alter_taller_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='fechas_no_laborables',
            field=models.JSONField(blank=True, default=list, help_text='Lista de fechas no disponibles. Formato: ["2024-12-25", "2025-01-01", ...]', verbose_name='Fechas No Laborables'),
        ),
    ]
