# Generated by Django 5.2.8 on 2026-01-05 05:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0006_taller_fechas_no_laborables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipovehiculo',
            options={'ordering': ['codigo_tramite', 'nombre'], 'verbose_name': 'Tipo de Trámite RTO', 'verbose_name_plural': 'Tipos de Trámites RTO'},
        ),
        migrations.AddField(
            model_name='tipovehiculo',
            name='codigo_tramite',
            field=models.CharField(blank=True, help_text='Código interno del trámite (ej: TRM-001)', max_length=20, verbose_name='Código de Trámite'),
        ),
        migrations.AddField(
            model_name='tipovehiculo',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de Creación'),
        ),
        migrations.AddField(
            model_name='tipovehiculo',
            name='precio_cajutad',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio para trámites con tarifa CAJUTAC', max_digits=10, null=True, verbose_name='Precio CAJUTAC'),
        ),
        migrations.AddField(
            model_name='tipovehiculo',
            name='precio_nacional',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio para trámites con tarifa nacional', max_digits=10, null=True, verbose_name='Precio Nacional'),
        ),
        migrations.AddField(
            model_name='tipovehiculo',
            name='precio_provincial',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio para trámites con tarifa provincial', max_digits=10, null=True, verbose_name='Precio Provincial'),
        ),
        migrations.AddField(
            model_name='tipovehiculo',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='tipovehiculo',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción adicional del trámite', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='tipovehiculo',
            name='nombre',
            field=models.CharField(help_text='Ej: RTO: AUTOS - PICK UP - UTILITARIO', max_length=200, verbose_name='Nombre del Trámite'),
        ),
        migrations.AlterField(
            model_name='tipovehiculo',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Campo legacy, usar precios específicos', max_digits=10, verbose_name='Precio (Legacy)'),
        ),
        migrations.AlterField(
            model_name='tipovehiculo',
            name='status',
            field=models.BooleanField(default=True, help_text='Indica si el trámite está disponible para reserva', verbose_name='Activo'),
        ),
    ]
