# Generated by Django 5.2.8 on 2026-01-05 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0007_alter_tipovehiculo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuraciontaller',
            options={'verbose_name': 'Configuración de Taller - Tipo Trámite', 'verbose_name_plural': 'Configuraciones de Talleres'},
        ),
    ]
