# Generated by Django 5.2.8 on 2026-01-05 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0008_alter_configuraciontaller_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuraciontaller',
            options={'verbose_name': 'Configuración de Taller - Tipo Trámite', 'verbose_name_plural': 'Configuración de Talleres - Tipos Trámite'},
        ),
    ]
