# Generated by Django 5.2.8 on 2026-01-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0009_alter_configuraciontaller_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuraciontaller',
            name='intervalo_minutos',
            field=models.IntegerField(default=30, help_text='Tiempo entre cada turno disponible', verbose_name='Intervalo entre turnos (minutos)'),
        ),
        migrations.AlterField(
            model_name='configuraciontaller',
            name='turnos_simultaneos',
            field=models.IntegerField(default=2, help_text='Cantidad de vehículos que pueden atenderse al mismo tiempo', verbose_name='Turnos Simultáneos'),
        ),
    ]
