# Generated by Django 5.2.8 on 2026-01-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0010_alter_configuraciontaller_intervalo_minutos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciontaller',
            name='status',
            field=models.BooleanField(default=True, help_text='Indica si este trámite está disponible en este taller', verbose_name='Disponible'),
        ),
    ]
