# Generated by Django 6.0.1 on 2026-01-15 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0011_configuraciontaller_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(blank=True, help_text='Marca del vehículo (ej: Ford, Chevrolet, Fiat)', max_length=100, null=True, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(blank=True, help_text='Modelo del vehículo (ej: Focus, Corsa, Palio)', max_length=100, null=True, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_vehiculo',
            field=models.ForeignKey(blank=True, help_text='Opcional - El tipo de trámite se define al crear el turno', null=True, on_delete=django.db.models.deletion.SET_NULL, to='talleres.tipovehiculo', verbose_name='Tipo de Vehículo'),
        ),
    ]
