# Generated by Django 6.0.1 on 2026-01-15 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0012_add_marca_modelo_to_vehiculo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuraciontaller',
            options={'verbose_name': 'Taller - Tipo Trámite', 'verbose_name_plural': 'Talleres - Tipos Trámite'},
        ),
    ]
