# Generated by Django 6.0.1 on 2026-01-15 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0013_alter_configuraciontaller_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipovehiculo',
            options={'ordering': ['codigo_tramite', 'nombre'], 'verbose_name': 'Tipo de Trámite', 'verbose_name_plural': 'Tipos de Trámites'},
        ),
    ]
