# Generated by Django 5.2.8 on 2026-02-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0015_add_default_tipo_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='whatsapp_operador',
            field=models.CharField(blank=True, help_text='Número con código de país sin +. Ej: 5493814123456', max_length=20, verbose_name='WhatsApp operador'),
        ),
    ]
