# Generated by Django 5.2.8 on 2026-02-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0016_taller_whatsapp_operador'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='email_operador',
            field=models.EmailField(blank=True, help_text='Email específico para recibir derivaciones del asistente virtual', max_length=254, verbose_name='Email operador'),
        ),
    ]
