# Generated by Django 6.0.1 on 2026-01-14 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Origen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('status', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Origen/Sector',
                'verbose_name_plural': 'Orígenes/Sectores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Permiso')),
                ('status', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Permiso de Usuario',
                'verbose_name_plural': 'Permisos de Usuario',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(blank=True, max_length=100, null=True, verbose_name='URL Home')),
                ('icon', models.CharField(blank=True, help_text='Clase de icono (ej: icon-home, fa fa-users)', max_length=50, null=True, verbose_name='Icono')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='panel_profile', to='auth.group', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Perfil de Grupo',
                'verbose_name_plural': 'Perfiles de Grupo',
            },
        ),
        migrations.CreateModel(
            name='MenuGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200, verbose_name='URL')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Menú')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
                ('status', models.BooleanField(default=True, verbose_name='Activo')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Grupo')),
                ('userPermission', models.ForeignKey(blank=True, help_text='Si se especifica, solo usuarios con este permiso verán este menú', null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel_administracion.userpermission', verbose_name='Permiso Requerido')),
            ],
            options={
                'verbose_name': 'Menú de Grupo',
                'verbose_name_plural': 'Menús de Grupo',
                'ordering': ['grupo', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel_administracion.origen', verbose_name='Origen/Sector')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='panel_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('userPermission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel_administracion.userpermission', verbose_name='Permiso')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
    ]
