# Generated by Django 6.0.1 on 2026-01-14 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_administracion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Origen',
            new_name='Sector',
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'ordering': ['nombre'], 'verbose_name': 'Sector', 'verbose_name_plural': 'Sectores'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='origen',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel_administracion.sector', verbose_name='Sector'),
        ),
    ]
