# Generated by Django 5.2.8 on 2026-01-26 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_administracion', '0002_rename_origen_to_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='origen',
            field=models.CharField(choices=[('ADMINISTRACION', 'Administracion'), ('TALLER', 'Taller')], default='ADMINISTRACION', help_text='Define el comportamiento al escanear QR de turnos', max_length=20, verbose_name='Origen/Tipo de Usuario'),
        ),
    ]
