# Generated by Django on 2026-01-25
# Data migration to add "Escanear Turno" menu option

from django.db import migrations


def agregar_menu_escanear_turno(apps, schema_editor):
    """
    Agrega la opcion 'Escanear Turno' al menu de los grupos que ya tienen
    opciones relacionadas con turnos.
    """
    MenuGrupo = apps.get_model('panel_administracion', 'MenuGrupo')

    # Buscar grupos que tienen menu de turnos
    grupos_con_turnos = MenuGrupo.objects.filter(
        url__icontains='turnos',
        status=True
    ).values_list('grupo_id', flat=True).distinct()

    for grupo_id in grupos_con_turnos:
        # Verificar si ya existe el menu
        existe = MenuGrupo.objects.filter(
            grupo_id=grupo_id,
            url='/panel/turnos/escanear/'
        ).exists()

        if not existe:
            # Obtener el orden maximo de los menus de turnos de ese grupo
            max_orden = MenuGrupo.objects.filter(
                grupo_id=grupo_id,
                url__icontains='turnos'
            ).order_by('-orden').values_list('orden', flat=True).first() or 0

            # Crear el nuevo menu
            MenuGrupo.objects.create(
                grupo_id=grupo_id,
                url='/panel/turnos/escanear/',
                nombre='Escanear Turno',
                orden=max_orden + 1,
                status=True,
                userPermission=None
            )


def eliminar_menu_escanear_turno(apps, schema_editor):
    """
    Elimina la opcion 'Escanear Turno' del menu.
    """
    MenuGrupo = apps.get_model('panel_administracion', 'MenuGrupo')
    MenuGrupo.objects.filter(url='/panel/turnos/escanear/').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('panel_administracion', '0003_userprofile_origen'),
    ]

    operations = [
        migrations.RunPython(
            agregar_menu_escanear_turno,
            eliminar_menu_escanear_turno
        ),
    ]
