# Generated by Django on 2026-01-25
# Data migration to add "Gestion Usuarios" menu option

from django.db import migrations


def agregar_menu_gestion_usuarios(apps, schema_editor):
    """
    Agrega la opcion 'Gestion Usuarios' al menu del grupo Administracion.
    """
    MenuGrupo = apps.get_model('panel_administracion', 'MenuGrupo')
    Group = apps.get_model('auth', 'Group')

    # Buscar grupo de Administracion
    try:
        grupo_admin = Group.objects.get(name='Administracion')
    except Group.DoesNotExist:
        # Si no existe el grupo Administracion, intentar con otros nombres comunes
        grupo_admin = Group.objects.filter(
            name__icontains='admin'
        ).first()

    if not grupo_admin:
        # Si no hay grupo de administracion, crear el menu para todos los grupos existentes
        grupos = Group.objects.all()
    else:
        grupos = [grupo_admin]

    for grupo in grupos:
        # Verificar si ya existe el menu
        existe = MenuGrupo.objects.filter(
            grupo=grupo,
            url='/panel/usuarios/'
        ).exists()

        if not existe:
            # Obtener el orden maximo de los menus de ese grupo
            max_orden = MenuGrupo.objects.filter(
                grupo=grupo
            ).order_by('-orden').values_list('orden', flat=True).first() or 0

            # Crear el nuevo menu
            MenuGrupo.objects.create(
                grupo=grupo,
                url='/panel/usuarios/',
                nombre='Gestion Usuarios',
                orden=max_orden + 1,
                status=True,
                userPermission=None
            )


def eliminar_menu_gestion_usuarios(apps, schema_editor):
    """
    Elimina la opcion 'Gestion Usuarios' del menu.
    """
    MenuGrupo = apps.get_model('panel_administracion', 'MenuGrupo')
    MenuGrupo.objects.filter(url='/panel/usuarios/').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('panel_administracion', '0004_agregar_menu_escanear_turno'),
    ]

    operations = [
        migrations.RunPython(
            agregar_menu_gestion_usuarios,
            eliminar_menu_gestion_usuarios
        ),
    ]
