# Generated by Django on 2026-01-26
# Migration to restructure Sector and Origen fields

from django.db import migrations, models


def crear_sectores_y_migrar_datos(apps, schema_editor):
    """
    1. Crea los sectores ADMINISTRACION y TALLER
    2. Migra los datos de origen a sector
    3. Actualiza origen a rol GENERAL
    """
    Sector = apps.get_model('panel_administracion', 'Sector')
    UserProfile = apps.get_model('panel_administracion', 'UserProfile')

    # Crear sectores si no existen
    sector_admin, _ = Sector.objects.get_or_create(
        codigo='ADMINISTRACION',
        defaults={'nombre': 'Administracion', 'status': True}
    )
    sector_taller, _ = Sector.objects.get_or_create(
        codigo='TALLER',
        defaults={'nombre': 'Taller', 'status': True}
    )

    # Migrar datos de origen a sector
    for profile in UserProfile.objects.all():
        if profile.origen == 'ADMINISTRACION':
            profile.sector = sector_admin
        elif profile.origen == 'TALLER':
            profile.sector = sector_taller
        else:
            # Por defecto, asignar a administracion
            profile.sector = sector_admin

        # Cambiar origen a GENERAL (rol por defecto)
        profile.origen = 'GENERAL'
        profile.save()


def revertir_migracion(apps, schema_editor):
    """
    Revierte la migracion: vuelve a poner los valores de sector en origen
    """
    UserProfile = apps.get_model('panel_administracion', 'UserProfile')

    for profile in UserProfile.objects.select_related('sector').all():
        if profile.sector:
            profile.origen = profile.sector.codigo
        else:
            profile.origen = 'ADMINISTRACION'
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('panel_administracion', '0005_agregar_menu_gestion_usuarios'),
    ]

    operations = [
        # 1. Agregar campo codigo a Sector (permitir null temporalmente)
        migrations.AddField(
            model_name='sector',
            name='codigo',
            field=models.CharField(
                blank=True,
                null=True,
                max_length=20,
                verbose_name='Codigo',
                help_text='Identificador unico del sector (ADMINISTRACION, TALLER)'
            ),
        ),

        # 2. Cambiar max_length de origen de 20 a 30
        migrations.AlterField(
            model_name='userprofile',
            name='origen',
            field=models.CharField(
                blank=True,
                choices=[
                    ('GERENTE', 'Gerente'),
                    ('RECURSOS_HUMANOS', 'Recursos Humanos'),
                    ('ADMINISTRATIVO', 'Administrativo'),
                    ('OPERARIO_AUTO', 'Operario Auto'),
                    ('OPERARIO_CAMION', 'Operario Camion'),
                    ('SUPERVISOR_TALLER', 'Supervisor Taller'),
                    ('GENERAL', 'General'),
                ],
                default='GENERAL',
                help_text='Rol especifico del usuario dentro del sector',
                max_length=30,
                null=True,
                verbose_name='Rol/Cargo'
            ),
        ),

        # 3. Actualizar help_text del campo sector
        migrations.AlterField(
            model_name='userprofile',
            name='sector',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.SET_NULL,
                to='panel_administracion.sector',
                verbose_name='Sector',
                help_text='Define el comportamiento al escanear QR de turnos (ADMINISTRACION o TALLER)'
            ),
        ),

        # 4. Ejecutar migracion de datos
        migrations.RunPython(
            crear_sectores_y_migrar_datos,
            revertir_migracion
        ),

        # 5. Hacer el campo codigo unique y not null
        migrations.AlterField(
            model_name='sector',
            name='codigo',
            field=models.CharField(
                max_length=20,
                unique=True,
                verbose_name='Codigo',
                help_text='Identificador unico del sector (ADMINISTRACION, TALLER)'
            ),
        ),
    ]
