# Generated by Django 5.2.8 on 2026-01-26 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_administracion', '0007_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='codigo',
            field=models.CharField(blank=True, help_text='Identificador unico del sector (ADMINISTRACION, TALLER)', max_length=20, null=True, unique=True, verbose_name='Codigo'),
        ),
    ]
