# Generated by Django 5.2.8 on 2026-02-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_administracion', '0008_alter_sector_codigo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupprofile',
            options={'ordering': ['orden'], 'verbose_name': 'Perfil de Grupo', 'verbose_name_plural': 'Perfiles de Grupo'},
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='orden',
            field=models.IntegerField(default=0, help_text='Orden de aparición en el menú sidebar (menor = primero)', verbose_name='Orden'),
        ),
    ]
