# Generated by Django on 2026-03-23
# Data migration to add "Gestión Sitio" menu option under Administración

from django.db import migrations


def agregar_menu_gestion_sitio(apps, schema_editor):
    """
    Agrega la opcion 'Gestión Sitio' al menu del grupo Administración.
    """
    MenuGrupo = apps.get_model('panel_administracion', 'MenuGrupo')
    Group = apps.get_model('auth', 'Group')

    # Buscar grupo de Administración
    try:
        grupo_admin = Group.objects.get(name='Administracion')
    except Group.DoesNotExist:
        grupo_admin = Group.objects.filter(
            name__icontains='admin'
        ).first()

    if not grupo_admin:
        grupos = Group.objects.all()
    else:
        grupos = [grupo_admin]

    for grupo in grupos:
        # Verificar si ya existe el menu
        existe = MenuGrupo.objects.filter(
            grupo=grupo,
            url='/panel/sitio/'
        ).exists()

        if not existe:
            # Obtener el orden maximo de los menus de ese grupo
            max_orden = MenuGrupo.objects.filter(
                grupo=grupo
            ).order_by('-orden').values_list('orden', flat=True).first() or 0

            # Crear el nuevo menu
            MenuGrupo.objects.create(
                grupo=grupo,
                url='/panel/sitio/',
                nombre='Gestión Sitio',
                orden=max_orden + 1,
                status=True,
                userPermission=None
            )


def eliminar_menu_gestion_sitio(apps, schema_editor):
    """
    Elimina la opcion 'Gestión Sitio' del menu.
    """
    MenuGrupo = apps.get_model('panel_administracion', 'MenuGrupo')
    MenuGrupo.objects.filter(url='/panel/sitio/').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('panel_administracion', '0010_set_group_orden_uso_ia_permission'),
    ]

    operations = [
        migrations.RunPython(
            agregar_menu_gestion_sitio,
            eliminar_menu_gestion_sitio
        ),
    ]
