# Generated by Django on 2026-03-23
# Data migration to add "Gestión Parámetros" menu option under Administración

from django.db import migrations


def agregar_menu_gestion_parametros(apps, schema_editor):
    MenuGrupo = apps.get_model('panel_administracion', 'MenuGrupo')
    Group = apps.get_model('auth', 'Group')

    try:
        grupo_admin = Group.objects.get(name='Administracion')
    except Group.DoesNotExist:
        grupo_admin = Group.objects.filter(name__icontains='admin').first()

    if not grupo_admin:
        grupos = Group.objects.all()
    else:
        grupos = [grupo_admin]

    for grupo in grupos:
        existe = MenuGrupo.objects.filter(
            grupo=grupo,
            url='/panel/parametros/'
        ).exists()

        if not existe:
            max_orden = MenuGrupo.objects.filter(
                grupo=grupo
            ).order_by('-orden').values_list('orden', flat=True).first() or 0

            MenuGrupo.objects.create(
                grupo=grupo,
                url='/panel/parametros/',
                nombre='Gestión Parámetros',
                orden=max_orden + 1,
                status=True,
                userPermission=None
            )


def eliminar_menu_gestion_parametros(apps, schema_editor):
    MenuGrupo = apps.get_model('panel_administracion', 'MenuGrupo')
    MenuGrupo.objects.filter(url='/panel/parametros/').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('panel_administracion', '0011_agregar_menu_gestion_sitio'),
    ]

    operations = [
        migrations.RunPython(
            agregar_menu_gestion_parametros,
            eliminar_menu_gestion_parametros
        ),
    ]
