# Generated by Django on 2026-03-23
# Mueve "Gestión Parámetros" del grupo Administración al grupo Turnos

from django.db import migrations


def mover_menu_parametros(apps, schema_editor):
    MenuGrupo = apps.get_model('panel_administracion', 'MenuGrupo')
    Group = apps.get_model('auth', 'Group')

    # Buscar grupo Turnos
    try:
        grupo_turnos = Group.objects.get(name='Turnos')
    except Group.DoesNotExist:
        grupo_turnos = Group.objects.filter(name__icontains='turno').first()

    if not grupo_turnos:
        return

    # Buscar el menú de parámetros (puede estar en cualquier grupo)
    menus_parametros = MenuGrupo.objects.filter(url='/panel/parametros/')

    if menus_parametros.exists():
        # Mover al grupo Turnos
        for menu in menus_parametros:
            menu.grupo = grupo_turnos
            # Ponerlo después del último menú del grupo Turnos
            max_orden = MenuGrupo.objects.filter(
                grupo=grupo_turnos
            ).order_by('-orden').values_list('orden', flat=True).first() or 0
            menu.orden = max_orden + 1
            menu.save()
    else:
        # Si no existe, crearlo en Turnos
        max_orden = MenuGrupo.objects.filter(
            grupo=grupo_turnos
        ).order_by('-orden').values_list('orden', flat=True).first() or 0

        MenuGrupo.objects.create(
            grupo=grupo_turnos,
            url='/panel/parametros/',
            nombre='Gestión Parámetros',
            orden=max_orden + 1,
            status=True,
            userPermission=None
        )


def revertir_menu_parametros(apps, schema_editor):
    MenuGrupo = apps.get_model('panel_administracion', 'MenuGrupo')
    Group = apps.get_model('auth', 'Group')

    try:
        grupo_admin = Group.objects.get(name='Administracion')
    except Group.DoesNotExist:
        grupo_admin = Group.objects.filter(name__icontains='admin').first()

    if not grupo_admin:
        return

    menus_parametros = MenuGrupo.objects.filter(url='/panel/parametros/')
    for menu in menus_parametros:
        menu.grupo = grupo_admin
        max_orden = MenuGrupo.objects.filter(
            grupo=grupo_admin
        ).order_by('-orden').values_list('orden', flat=True).first() or 0
        menu.orden = max_orden + 1
        menu.save()


class Migration(migrations.Migration):

    dependencies = [
        ('panel_administracion', '0013_agregar_menu_gestion_parametros'),
    ]

    operations = [
        migrations.RunPython(
            mover_menu_parametros,
            revertir_menu_parametros
        ),
    ]
