# Generated by Django on 2026-03-23
# Renombra "Gestión Parámetros" a "Configuraciones"

from django.db import migrations


def renombrar(apps, schema_editor):
    MenuGrupo = apps.get_model('panel_administracion', 'MenuGrupo')
    MenuGrupo.objects.filter(url='/panel/parametros/').update(nombre='Configuraciones')


def revertir(apps, schema_editor):
    MenuGrupo = apps.get_model('panel_administracion', 'MenuGrupo')
    MenuGrupo.objects.filter(url='/panel/parametros/').update(nombre='Gestión Parámetros')


class Migration(migrations.Migration):

    dependencies = [
        ('panel_administracion', '0014_mover_menu_parametros_a_turnos'),
    ]

    operations = [
        migrations.RunPython(renombrar, revertir),
    ]
