# Generated by Django on 2026-03-23
# Mueve "Configuración" al final del menú Asistente IA

from django.db import migrations


def reordenar(apps, schema_editor):
    MenuGrupo = apps.get_model('panel_administracion', 'MenuGrupo')
    Group = apps.get_model('auth', 'Group')

    try:
        grupo = Group.objects.get(name='Asistente IA')
    except Group.DoesNotExist:
        return

    menus = MenuGrupo.objects.filter(grupo=grupo).order_by('orden')
    orden_map = {
        '/panel/asistente/dashboard/': 1,
        '/panel/asistente/faqs/': 2,
        '/panel/asistente/kb/': 3,
        '/panel/asistente/conversaciones/': 4,
        '/panel/asistente/sugerencias/': 5,
        '/panel/asistente/uso-ia/': 6,
        '/panel/asistente/config/': 7,
    }

    for menu in menus:
        nuevo_orden = orden_map.get(menu.url)
        if nuevo_orden and menu.orden != nuevo_orden:
            menu.orden = nuevo_orden
            menu.save()


def revertir(apps, schema_editor):
    MenuGrupo = apps.get_model('panel_administracion', 'MenuGrupo')
    Group = apps.get_model('auth', 'Group')

    try:
        grupo = Group.objects.get(name='Asistente IA')
    except Group.DoesNotExist:
        return

    orden_map = {
        '/panel/asistente/dashboard/': 1,
        '/panel/asistente/config/': 2,
        '/panel/asistente/faqs/': 3,
        '/panel/asistente/kb/': 4,
        '/panel/asistente/conversaciones/': 5,
        '/panel/asistente/sugerencias/': 6,
        '/panel/asistente/uso-ia/': 7,
    }

    for menu in MenuGrupo.objects.filter(grupo=grupo):
        nuevo_orden = orden_map.get(menu.url)
        if nuevo_orden:
            menu.orden = nuevo_orden
            menu.save()


class Migration(migrations.Migration):

    dependencies = [
        ('panel_administracion', '0015_renombrar_menu_configuraciones'),
    ]

    operations = [
        migrations.RunPython(reordenar, revertir),
    ]
