# Generated by Django 6.0.1 on 2026-03-29 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_administracion', '0016_reordenar_menu_asistente_config_al_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='menus_permitidos',
            field=models.ManyToManyField(blank=True, help_text='Submenús específicos a los que el usuario tiene acceso', related_name='usuarios_permitidos', to='panel_administracion.menugrupo', verbose_name='Submenús Permitidos'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userPermission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel_administracion.userpermission', verbose_name='Permiso (legacy)'),
        ),
    ]
