# Generated by Django 5.2.8 on 2026-01-04 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('talleres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, help_text='Código único generado automáticamente', max_length=10, unique=True, verbose_name='Código de Turno')),
                ('fecha', models.DateField(verbose_name='Fecha del Turno')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Finalización')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('EN_CURSO', 'En Curso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado'), ('NO_ASISTIO', 'No Asistió')], default='PENDIENTE', max_length=20, verbose_name='Estado del Turno')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre el turno', verbose_name='Observaciones')),
                ('email_enviado', models.BooleanField(default=False, verbose_name='Email de Confirmación Enviado')),
                ('whatsapp_enviado', models.BooleanField(default=False, verbose_name='WhatsApp Enviado')),
                ('recordatorio_enviado', models.BooleanField(default=False, verbose_name='Recordatorio Enviado')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='turnos/qr/', verbose_name='Código QR')),
                ('token_cancelacion', models.CharField(editable=False, help_text='Token único para cancelar el turno', max_length=64, unique=True, verbose_name='Token de Cancelación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('cliente', models.ForeignKey(help_text='Cliente que agenda el turno', on_delete=django.db.models.deletion.CASCADE, related_name='turnos_rtv', to='clientes.cliente', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuario que creó el turno (para turnos desde el admin)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='talleres.taller', verbose_name='Taller')),
                ('tipo_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleres.tipovehiculo', verbose_name='Tipo de Trámite')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='talleres.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['-fecha', '-hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='HistorialTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(help_text='Tipo de acción realizada (creación, modificación, cancelación, etc.)', max_length=50, verbose_name='Acción')),
                ('descripcion', models.TextField(help_text='Detalle de la acción realizada', verbose_name='Descripción')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que realizó la acción (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='turnero.turno', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Historial de Turno',
                'verbose_name_plural': 'Historial de Turnos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['fecha', 'taller'], name='turnero_tur_fecha_121ff1_idx'),
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['codigo'], name='turnero_tur_codigo_9baf87_idx'),
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['estado'], name='turnero_tur_estado_4f74ad_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='turno',
            unique_together={('taller', 'fecha', 'hora_inicio')},
        ),
    ]
