# Generated by Django 5.2.8 on 2026-01-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='token_expiracion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de expiración del token de reprogramación', null=True, verbose_name='Expiración del Token'),
        ),
        migrations.AddField(
            model_name='turno',
            name='token_reprogramacion',
            field=models.CharField(blank=True, editable=False, help_text='Token único para permitir reprogramación segura del turno', max_length=64, null=True, unique=True, verbose_name='Token de Reprogramación'),
        ),
    ]
