# Generated by Django 6.0.1 on 2026-01-15 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0012_add_marca_modelo_to_vehiculo'),
        ('turnero', '0002_turno_token_expiracion_turno_token_reprogramacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaTemporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha del Turno')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('session_key', models.CharField(help_text='Identificador único de la sesión del usuario', max_length=40, verbose_name='Clave de Sesión')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('expira_at', models.DateTimeField(help_text='Momento en que la reserva expira automáticamente', verbose_name='Fecha de Expiración')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_temporales', to='talleres.taller', verbose_name='Taller')),
                ('tipo_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleres.tipovehiculo', verbose_name='Tipo de Vehículo')),
            ],
            options={
                'verbose_name': 'Reserva Temporal',
                'verbose_name_plural': 'Reservas Temporales',
                'indexes': [models.Index(fields=['expira_at'], name='turnero_res_expira__767478_idx'), models.Index(fields=['session_key'], name='turnero_res_session_7f901b_idx'), models.Index(fields=['taller', 'fecha', 'hora_inicio'], name='turnero_res_taller__348133_idx')],
                'unique_together': {('taller', 'tipo_vehiculo', 'fecha', 'hora_inicio', 'session_key')},
            },
        ),
    ]
