# Generated by Django 5.2.8 on 2026-01-26 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnero', '0003_add_reserva_temporal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='atendido_por',
            field=models.ForeignKey(blank=True, help_text='Usuario del taller que registro la atencion del turno', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_atendidos', to=settings.AUTH_USER_MODEL, verbose_name='Atendido por'),
        ),
        migrations.AddField(
            model_name='turno',
            name='fecha_atencion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se registro la atencion del turno', null=True, verbose_name='Fecha de Atencion'),
        ),
    ]
