# Generated by Django 5.2.8 on 2026-02-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnero', '0004_turno_atendido_por_turno_fecha_atencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='token_cancelacion_expiracion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de expiración del token de cancelación', null=True, verbose_name='Expiración del Token de Cancelación'),
        ),
    ]
