# Generated by Django 5.0.2 on 2025-11-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='orden',
            field=models.IntegerField(blank=True, help_text='Orden de aparición en la lista', null=True),
        ),
    ]
# Eliminado para limpieza de migraciones
