# Generated by Django 5.2.8 on 2026-01-04 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorios', '0001_initial'),
        ('ubicacion', '0002_ubicacion_orden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ubicacion',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Ubicación', 'verbose_name_plural': 'Ubicaciones'},
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ubicaciones', to='territorios.localidad', verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='direccion',
            field=models.CharField(max_length=255, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='horario',
            field=models.CharField(blank=True, max_length=255, verbose_name='Horario de atención'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='latitud',
            field=models.FloatField(verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='longitud',
            field=models.FloatField(verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='orden',
            field=models.IntegerField(blank=True, help_text='Orden de aparición en la lista', null=True, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='provincia',
            field=models.CharField(default='Jujuy', max_length=100, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, verbose_name='Teléfono'),
        ),
    ]
