# Generated by Django 5.2.8 on 2026-01-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicacion', '0003_alter_ubicacion_options_ubicacion_localidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
    ]
