# Generated by Django 5.2.8 on 2026-01-04 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('territorios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='DNI')),
                ('cuit', models.CharField(blank=True, max_length=11, null=True, verbose_name='CUIT')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('celular', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('domicilio', models.CharField(blank=True, max_length=300, null=True, verbose_name='Domicilio')),
                ('status', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='territorios.localidad', verbose_name='Localidad')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clientes.persona')),
                ('estado_cliente', models.CharField(choices=[('ACTIVO', 'Activo'), ('PENDIENTE_DOCUMENTACION', 'Pendiente de Documentación'), ('PENDIENTE_PAGO', 'Pendiente de Pago'), ('DOCUMENTACION_INCOMPLETA', 'Documentación Incompleta'), ('BLOQUEADO', 'Bloqueado'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=30, verbose_name='Estado del Cliente')),
                ('tiene_turnos_pendientes', models.BooleanField(default=False, verbose_name='Tiene Turnos Pendientes')),
                ('cantidad_turnos_realizados', models.IntegerField(default=0, verbose_name='Turnos Realizados')),
                ('cantidad_turnos_cancelados', models.IntegerField(default=0, verbose_name='Turnos Cancelados')),
                ('ultimo_turno_fecha', models.DateField(blank=True, null=True, verbose_name='Último Turno')),
                ('documentacion_completa', models.BooleanField(default=False, verbose_name='Documentación Completa')),
                ('documentos_faltantes', models.TextField(blank=True, help_text='Lista de documentos que faltan', null=True, verbose_name='Documentos Faltantes')),
                ('notas_internas', models.TextField(blank=True, help_text='Observaciones del personal administrativo', null=True, verbose_name='Notas Internas')),
                ('acepta_whatsapp', models.BooleanField(default=True, verbose_name='Acepta WhatsApp')),
                ('acepta_email', models.BooleanField(default=True, verbose_name='Acepta Email')),
                ('acepta_sms', models.BooleanField(default=False, verbose_name='Acepta SMS')),
                ('cliente_activo', models.BooleanField(default=True, verbose_name='Cliente Activo')),
                ('fecha_registro_cliente', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['apellido', 'nombre'],
            },
            bases=('clientes.persona',),
        ),
    ]
