# Generated by Django 5.2.8 on 2026-01-05 04:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarifa',
            options={'ordering': ['-created'], 'verbose_name': 'Tarifa', 'verbose_name_plural': 'Tarifas'},
        ),
        migrations.AddField(
            model_name='tarifa',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de Creación'),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='status',
            field=models.BooleanField(default=False, help_text='Marca esta tarifa como vigente. Solo puede haber una tarifa vigente a la vez.', verbose_name='Vigente'),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='archivo_excel',
            field=models.FileField(blank=True, null=True, upload_to='tarifas/', verbose_name='Archivo Excel'),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
